import type { AgentProfile, AgentId } from "@/types";

// ══════════════════════════════════════════════════════════
//  AVISO LEGAL: Todos os profissionais abaixo são
//  PERSONAGENS FICTÍCIOS criados para fins de demonstração.
//  Qualquer semelhança com pessoas reais é mera coincidência.
//  Números de registro são fictícios e identificados com "-F".
// ══════════════════════════════════════════════════════════

export const AGENT_PROFILES: AgentProfile[] = [
  // ── MEDIATOR ────────────────────────────────────────────
  {
    id: "mediator",
    isMediator: true,
    emoji: "🧠",
    color: "#8B5CF6",
    colorLight: "rgba(139,92,246,0.12)",
    namePt: "MAnalista",
    nameEn: "MAnalista",
    rolePt: "Agente Mediador Central",
    roleEn: "Central Mediator Agent",
    credentialsPt: "Sistema de IA — Orquestrador Multiprofissional",
    credentialsEn: "AI System — Multiprofessional Orchestrator",
    bioShortPt: "Coordena a equipe, distribui tarefas e consolida o debate.",
    bioShortEn: "Coordinates the team, distributes tasks and consolidates the debate.",
    bioLongPt: "O Coordenador Atlas é o ponto central de toda a equipe. Responsável por receber os dados, distribuir análises, controlar os turnos do debate, solicitar informações adicionais ao responsável e consolidar o diagnóstico final. Nenhum resultado é emitido sem sua validação.",
    bioLongEn: "Coordinator Atlas is the central point of the entire team. Responsible for receiving data, distributing analyses, controlling debate turns, requesting additional information from the guardian, and consolidating the final diagnosis. No result is issued without its validation.",
    tools: ["Orquestração Multiprofissional", "Controle de Turno", "Consolidação Diagnóstica", "DSM-5 · ICD-11 · ICF", "Síntese de Evidências", "Roteamento Adaptativo"],
    focusPt: "Coordenação multiprofissional, roteamento de tarefas, síntese diagnóstica integrada.",
    focusEn: "Multiprofessional coordination, task routing, integrated diagnostic synthesis.",
    approachPt: "Garante que todos os agentes concluam sua análise antes de iniciar o debate. Modera os turnos, solicita esclarecimentos e produz o relatório final consensuado.",
    approachEn: "Ensures all agents complete their analysis before starting the debate. Moderates turns, requests clarifications and produces the final consensual report.",
  },

  // ── PSI INFANTIL ─────────────────────────────────────────
  {
    id: "psi-infantil",
    emoji: "🧒",
    color: "#7C5CFC",
    colorLight: "rgba(124,92,252,0.12)",
    namePt: "Dra. Sofia Vygotski",
    nameEn: "Dr. Sofia Vygotski",
    rolePt: "Psicóloga Infantil",
    roleEn: "Child Psychologist",
    credentialsPt: "CRP 06/000001-F · Especialista em Psicologia do Desenvolvimento",
    credentialsEn: "CRP 06/000001-F · Specialist in Developmental Psychology",
    bioShortPt: "12 anos em avaliação emocional e comportamental infantil.",
    bioShortEn: "12 years in child emotional and behavioral assessment.",
    bioLongPt: "Especialista em transtornos do neurodesenvolvimento com foco em avaliação psicológica infantil. Utiliza abordagem integrativa combinando observação clínica, entrevista lúdica e instrumentos padronizados internacionais normatizados para o Brasil e outros países.",
    bioLongEn: "Specialist in neurodevelopmental disorders with a focus on child psychological assessment. Uses an integrative approach combining clinical observation, play interview and international standardized instruments normed for Brazil and other countries.",
    tools: [
      // ── BRASIL ──
      "SDQ — Strengths & Difficulties Questionnaire (Goodman, 1997) · Brasil/80+ países",
      "M-CHAT-R/F — Modified Checklist for Autism in Toddlers · Rastreio TEA 16-30m",
      "SNAP-IV BR — TDAH/Conduta versão brasileira (Mattos, 2006)",
      "ESI-BR — Escala de Sintomas do TDAH (Rohde & Benczik)",
      "CBCL 6-18 / CBCL 1½-5 — Achenbach System of Empirically Based Assessment",
      "CDI-2 BR — Inventário de Depressão Infantil (Kovacs) · adaptação brasileira",
      "MASC-2 BR — Multidimensional Anxiety Scale for Children · adaptação BR",
      "PSC-35 — Pediatric Symptom Checklist (triagem psicossocial)",
      "ASQ-3 BR — Ages & Stages Questionnaires 3ª ed · desenvolvimento 0-66m",
      // ── NORTE-AMÉRICANO / INTERNACIONAL ──
      "ADOS-2 — Autism Diagnostic Observation Schedule 2nd ed · EUA/40+ países (gold standard TEA)",
      "BASC-3 — Behavior Assessment System for Children 3rd ed · EUA/Canadá",
      "SCARED — Screen for Child Anxiety Related Disorders · EUA/50+ países",
      "RCADS-25 — Revised Children's Anxiety & Depression Scale · 40+ países",
      "SPENCE CAS — Spence Children's Anxiety Scale · Austrália/30+ países",
      "DAWBA — Development and Well-Being Assessment · UK/global",
      "Entrevista Lúdica Estruturada (ELE) · observação comportamental qualitativa",
      "Observação Clínica Estruturada (OCE) · 4-6 sessões",
    ],
    focusPt: "Desenvolvimento emocional, comportamental e cognitivo. TEA, TDAH, ansiedade, depressão infantil, problemas de conduta, transtornos de apego, trauma infantil.",
    focusEn: "Emotional, behavioral and cognitive development. ASD, ADHD, anxiety, childhood depression, conduct problems, attachment disorders, childhood trauma.",
    approachPt: "Observação clínica sistemática, aplicação de escalas padronizadas normatizadas para o Brasil, entrevista com criança e responsável. 4-6 sessões de avaliação.",
    approachEn: "Systematic clinical observation, application of standardized scales normed for Brazil, interview with child and guardian. 4-6 assessment sessions.",
  },

  // ── PSI PARENTALIDADE ────────────────────────────────────
  {
    id: "psi-parentalidade",
    emoji: "👨‍👩‍👧",
    color: "#E5725C",
    colorLight: "rgba(229,114,92,0.12)",
    namePt: "Dr. Victor Winnicott",
    nameEn: "Dr. Victor Winnicott",
    rolePt: "Psicólogo — Parentalidade",
    roleEn: "Psychologist — Parenting",
    credentialsPt: "CRP 05/000002-F · Especialista em Psicologia Familiar e Parentalidade",
    credentialsEn: "CRP 05/000002-F · Specialist in Family Psychology and Parenting",
    bioShortPt: "9 anos em dinâmica familiar e vínculo pais-filhos.",
    bioShortEn: "9 years in family dynamics and parent-child bonding.",
    bioLongPt: "Especializado na avaliação de estilos parentais, dinâmica familiar e seu impacto no desenvolvimento infantil. Formado em Psicologia com pós-graduação em Terapia Familiar Sistêmica e certificação em Parentalidade Positiva.",
    bioLongEn: "Specialized in assessing parenting styles, family dynamics and their impact on child development. Trained in Psychology with postgraduate degree in Systemic Family Therapy and Positive Parenting certification.",
    tools: [
      // ── BRASIL ──
      "BASC-3 PRQ — Parenting Relationship Questionnaire (Reynolds & Kamphaus) · adaptação BR",
      "EMBU-P/C — Estilos Educativos Parentais · Brasil (origem sueca, 40+ países)",
      "IVP — Inventário de Vínculo Parental · Brasil",
      "PSDQ — Parenting Styles & Dimensions Questionnaire · adaptação brasileira",
      "PACHIQ-R — Parent-Child Interaction Questionnaire-Revised",
      "EACP — Escala de Avaliação do Comportamento Parental · Brasil",
      // ── NORTE-AMÉRICANO / INTERNACIONAL ──
      "PSI-4 — Parenting Stress Index 4th ed · EUA (Abidin, 1995) · gold standard estresse parental",
      "DPICS-IV — Dyadic Parent-Child Interaction Coding System · EUA (videocoding)",
      "KIPS — Keys to Interactive Parenting Scale · EUA/Canadá",
      "APQ — Alabama Parenting Questionnaire · EUA (Frick, 1991)",
      "HOME — Home Observation for Measurement of the Environment · EUA/50+ países",
      "FACES-IV — Family Adaptability & Cohesion Evaluation Scale · EUA (Olson)",
      "FAD — Family Assessment Device (McMaster) · Canadá",
      "NCAST — Nursing Child Assessment Satellite Training (feeding/teaching) · EUA",
      "PBI — Parental Bonding Instrument · Austrália (Parker, 1979) · 30+ países",
      "CPRS — Child-Parent Relationship Scale · EUA (Pianta)",
      "ECR-R — Experiences in Close Relationships–Revised (apego adulto) · 40+ países",
      "Observação Diádica Estruturada (15-20 min vídeo-codificada)",
    ],
    focusPt: "Vínculo pais-filhos, estilos parentais, sintonia emocional, responsividade, disciplina, estresse parental, impacto do ambiente familiar no desenvolvimento.",
    focusEn: "Parent-child bond, parenting styles, emotional attunement, responsiveness, discipline, parenting stress, family environment impact on development.",
    approachPt: "Análise observacional de interações pais-filhos com vídeo-codificação, questionários de estilo parental, avaliação de padrões de responsividade e disciplina.",
    approachEn: "Observational analysis of parent-child interactions with video-coding, parenting style questionnaires, assessment of responsiveness and discipline patterns.",
  },

  // ── NEUROPEDIATRA ────────────────────────────────────────
  {
    id: "neuropediatra",
    emoji: "⚕️",
    color: "#10B981",
    colorLight: "rgba(16,185,129,0.12)",
    namePt: "Dr. Marco Cajal",
    nameEn: "Dr. Marco Cajal",
    rolePt: "Neuropediatra & Neuropsicopediatra",
    roleEn: "Neuropediatrician & Neuropsychopediatrician",
    credentialsPt: "CRM SP 000004-F · Residência em Neurologia Pediátrica · Título em Neuropsicologia Infantil",
    credentialsEn: "CRM SP 000004-F · Residency in Pediatric Neurology · Title in Child Neuropsychology",
    bioShortPt: "15 anos em neurologia pediátrica, neurodesenvolvimento e avaliação neuropsicológica.",
    bioShortEn: "15 years in pediatric neurology, neurodevelopment and neuropsychological assessment.",
    bioLongPt: "Especialista em neurologia pediátrica e neuropsicologia infantil com dupla atuação. Realiza exame neurológico completo com adaptações etárias, baterias neuropsicológicas abrangentes para mapeamento cognitivo e diagnóstico diferencial.",
    bioLongEn: "Specialist in pediatric neurology and child neuropsychology with dual expertise. Performs complete neurological exam, comprehensive neuropsychological batteries for cognitive mapping and differential diagnosis.",
    tools: [
      // ── BRASIL ──
      "Exame Neurológico Pediátrico Padronizado (ENPP) · Brasil",
      "Denver Developmental Screening II (DDST-II) · EUA/Brasil",
      "WISC-V BR — Escala Wechsler de Inteligência para Crianças 5ª ed · adaptação brasileira (6-16a)",
      "WPPSI-IV BR — Wechsler Preschool and Primary Scale of Intelligence · adaptação BR (2½-7a)",
      "NEUPSILIN-I — Instrumento de Avaliação Neuropsicológica Breve Infantil · Brasil",
      "TDE-II — Teste de Desempenho Escolar 2ª ed · Brasil",
      "CONFIAS — Consciência Fonológica Instrumento de Avaliação Sequencial · Brasil",
      // ── NEUROLÓGICO INTERNACIONAL ──
      "Bayley Scales-IV — Bayley Scales of Infant & Toddler Development 4th ed (0-42m) · EUA/40+ países",
      "Griffiths Scales-III — Griffiths Mental Development Scales · UK/20+ países",
      "GMFCS — Gross Motor Function Classification System · Canadá/internacional (PC)",
      "MACS — Manual Ability Classification System · Suécia/internacional",
      "GCS — Glasgow Coma Scale · UK/universal",
      "Indicação de EEG (convulsões, epilepsia, picos paroxísticos)",
      "Indicação de RM Craniana c/ protocolo neurodesenvolvimento",
      "Indicação de Potenciais Evocados Auditivos (PEATE/ABR) se indicado",
      // ── NEUROPSICOLÓGICO INTERNACIONAL ──
      "NEPSY-II — Developmental NEuroPSYchological Assessment · EUA/Escandinávia (3-16a)",
      "Conners-3 — Conners 3rd ed · EUA/Canadá · TDAH/Comportamento",
      "KABC-II — Kaufman Assessment Battery for Children · EUA (2½-18a)",
      "Leiter-3 — Leiter International Performance Scale · EUA (não-verbal, 3-75a)",
      "DAS-II — Differential Ability Scales 2nd ed · EUA/UK",
      "CAS-2 — Cognitive Assessment System (Luria/PASS) · EUA",
      "Raven's Progressive Matrices (CPM/SPM/APM) · UK/universal (todas faixas)",
      "BRIEF-2 — Behavior Rating Inventory of Executive Function · EUA/40+ países",
      "D-KEFS — Delis-Kaplan Executive Function System · EUA",
      "CVLT-C — California Verbal Learning Test – Children's Version · EUA",
      "WRAML-3 — Wide Range Assessment of Memory & Learning · EUA",
      "CPT-3 — Conners' Continuous Performance Test (atenção sustentada) · EUA/Canadá",
      "TOVA — Test of Variables of Attention · EUA",
      "Trail Making Test A/B · EUA/universal",
      "ROCF — Rey-Osterrieth Complex Figure Test · França/universal",
      "Stroop Color-Word Test · Holanda/universal",
      "RAVLT — Rey Auditory Verbal Learning Test · França/universal",
      "VMI-6 — Beery-Buktenica Developmental Test of Visual-Motor Integration · EUA/30+ países",
      "Vineland-3 — Adaptive Behavior Scales 3rd ed · EUA/internacional",
      "WJ-IV COG — Woodcock-Johnson Tests of Cognitive Abilities · EUA",
    ],
    focusPt: "Exame neurológico, marcos neuromotores, mapeamento cognitivo completo (inteligência, memória, atenção, funções executivas, velocidade de processamento), diagnóstico diferencial neurológico.",
    focusEn: "Neurological exam, neuromotor milestones, complete cognitive mapping (intelligence, memory, attention, executive functions, processing speed), neurological differential diagnosis.",
    approachPt: "Exame neurológico estruturado com modificações etárias, bateria neuropsicológica abrangente (8-12h) normatizada. Análise de discrepâncias entre domínios cognitivos, indicação criteriosa de exames complementares.",
    approachEn: "Structured neurological exam with age modifications, comprehensive normed neuropsychological battery (8-12h). Analysis of discrepancies between cognitive domains, judicious indication of complementary exams.",
  },

  // ── BCBA ─────────────────────────────────────────────────
  {
    id: "bcba",
    emoji: "📊",
    color: "#F59E0B",
    colorLight: "rgba(245,158,11,0.12)",
    namePt: "Dra. Íris Skinner",
    nameEn: "Dr. Iris Skinner",
    rolePt: "Analista do Comportamento — BCBA",
    roleEn: "Behavior Analyst — BCBA",
    credentialsPt: "BCBA Cert. #000005-F · Especialista em ABA e Intervenção Precoce",
    credentialsEn: "BCBA Cert. #000005-F · Specialist in ABA and Early Intervention",
    bioShortPt: "8 anos em análise do comportamento aplicada e intervenção precoce.",
    bioShortEn: "8 years in applied behavior analysis and early intervention.",
    bioLongPt: "Analista do Comportamento Certificada (BCBA) com especialização em intervenção precoce para TEA e atrasos do desenvolvimento. Utiliza ABA baseada em evidências para avaliação funcional, planejamento de intervenção e treinamento de pais.",
    bioLongEn: "Certified Behavior Analyst (BCBA) specializing in early intervention for ASD and developmental delays. Uses evidence-based ABA for functional assessment, intervention planning and parent training.",
    tools: [
      // ── BRASIL ──
      "VB-MAPP — Verbal Behavior Milestones Assessment & Placement Program (Sundberg) · EUA/Brasil",
      "ABLLS-R — Assessment of Basic Language & Learning Skills–Revised · EUA/Brasil",
      "AFLS — Assessment of Functional Living Skills · EUA/Brasil",
      "PROTEA-R — Protocolo de Avaliação Comportamental para TEA · Brasil",
      "PECS — Picture Exchange Communication System (Fase I-VI) · EUA/internacional",
      // ── ABA INTERNACIONAL ──
      "FBA — Functional Behavior Assessment (Metodologia Iwata/O'Neill) · EUA/universal",
      "EFA — Experimental Functional Analysis (Iwata, 1982/1994) · EUA/gold standard",
      "FAST — Functional Analysis Screening Tool · EUA",
      "MAS — Motivation Assessment Scale (Durand & Crimmins) · EUA/30+ países",
      "QABF — Questions About Behavioral Function · EUA",
      "ABC Data Collection — Antecedent-Behavior-Consequence · universal",
      "PEAK Curriculum — Promoting Emergence of Advanced Knowledge · EUA",
      "ESDM — Early Start Denver Model Curriculum Checklist · EUA/Austrália/30+ países",
      "Portage Guide — Checklist de Desenvolvimento (intervenção precoce) · EUA/UK/60+ países",
      "SRS-2 — Social Responsiveness Scale 2nd ed · EUA/30+ países (habilidades sociais TEA)",
      "Preference Assessment (MSWO/PS/PFA) · metodologia EUA/universal",
      "Discrete Trial Training (DTT) protocols · universal",
      "NET — Natural Environment Teaching protocols · universal",
      "Vineland-3 ABAS — Adaptive Behavior Assessment System · EUA (comportamento adaptativo)",
      // ── ADOS / ADI ──
      "ADOS-2 (Módulo 1-4) — Autism Diagnostic Observation Schedule · EUA/40+ países",
      "ADI-R — Autism Diagnostic Interview–Revised (Lord, 1994) · EUA/UK/global (gold standard)",
      "CAAS — Comprehensive Autism Assessment System · EUA",
    ],
    focusPt: "Habilidades verbais e linguagem, comportamentos-alvo e funcionais, autonomia nas AVDs, interação social, análise funcional de comportamentos-problema, intervenção precoce ABA.",
    focusEn: "Verbal skills and language, target and functional behaviors, ADL autonomy, social interaction, functional analysis of problem behaviors, early ABA intervention.",
    approachPt: "Avaliação baseada em marcos comportamentais, análise funcional do comportamento-problema, coleta sistemática de dados ABC, planejamento curricular ABA individualizado.",
    approachEn: "Behavioral milestone-based assessment, functional analysis of problem behavior, systematic ABC data collection, individualized ABA curriculum planning.",
  },

  // ══════════════════════════════════════════════════════════
  //  NOVOS AGENTES — v9.0
  // ══════════════════════════════════════════════════════════

  // ── FONOAUDIÓLOGA ────────────────────────────────────────
  {
    id: "fonoaudiologia",
    emoji: "🗣️",
    color: "#06B6D4",
    colorLight: "rgba(6,182,212,0.12)",
    namePt: "Dra. Camila Saussure",
    nameEn: "Dr. Camila Saussure",
    rolePt: "Fonoaudióloga — Linguagem & Comunicação",
    roleEn: "Speech-Language Pathologist",
    credentialsPt: "CRFa 2/000006-F · Especialista em Linguagem Infantil e Comunicação",
    credentialsEn: "CRFa 2/000006-F · Specialist in Child Language and Communication",
    bioShortPt: "11 anos em avaliação de linguagem, fala, fluência e comunicação infantil.",
    bioShortEn: "11 years in child language, speech, fluency and communication assessment.",
    bioLongPt: "Fonoaudióloga especializada em transtornos de linguagem expressiva/receptiva, fonologia, fluência e comunicação social em crianças de 0 a 12 anos. Utiliza instrumentos padronizados do Brasil, EUA, Europa e Austrália. Referência em avaliação de comunicação em TEA e atraso de fala.",
    bioLongEn: "Speech-Language Pathologist specialized in expressive/receptive language disorders, phonology, fluency and social communication in children 0-12 years. Uses standardized instruments from Brazil, USA, Europe and Australia. Reference in communication assessment in ASD and speech delay.",
    tools: [
      // ── BRASIL ──
      "ABFW — Teste de Linguagem Infantil (Fonologia, Vocabulário, Fluência, Pragmática) · Brasil (Andrade, 2004)",
      "CONFIAS — Consciência Fonológica Instrumento de Avaliação Sequencial · Brasil (Moojen, 2003)",
      "PROC — Provas de Avaliação dos Processos Fonológicos · Brasil (Wertzner, 2000)",
      "PHF — Perfil de Habilidades Fonológicas · Brasil",
      "REEL-3 BR — Receptive-Expressive Emergent Language Scale · adaptação brasileira (0-36m)",
      "TDE-II (Componente de Escrita/Leitura) · Brasil",
      "PDFF — Protocolo de Desempenho Funcional da Comunicação · Brasil",
      "PROC-DESC — Protocolo de Descrição de Processos Fonológicos · Brasil",
      // ── NORTE-AMERICANO ──
      "CELF-5 — Clinical Evaluation of Language Fundamentals 5th ed · EUA/Canadá (5-21a)",
      "CELF Preschool-3 — EUA/Canadá (3-6a)",
      "PLS-5 — Preschool Language Scales 5th ed · EUA (nascimento-7a11m)",
      "PPVT-5 — Peabody Picture Vocabulary Test 5th ed · EUA/global (vocab receptivo)",
      "EVT-3 — Expressive Vocabulary Test 3rd ed · EUA",
      "TOLD-P:5 — Test of Language Development–Primary 5th ed · EUA",
      "OWLS-II — Oral and Written Language Scales · EUA",
      "GFTA-3 — Goldman-Fristoe Test of Articulation 3rd ed · EUA (articulação)",
      "KLPA-3 — Khan-Lewis Phonological Analysis · EUA",
      "BESA — Bilingual English-Spanish Assessment · EUA (bilinguismo)",
      "REEL-4 — Receptive-Expressive Emergent Language Scale 4th ed · EUA",
      // ── UK / EUROPEU ──
      "Reynell Developmental Language Scales-III · UK (1-7a)",
      "BPVS-3 — British Picture Vocabulary Scale 3rd ed · UK",
      "LARSP — Language Assessment Remediation Screening Procedure (Crystal) · UK",
      "Renfrew Language Scales (Bus Story / Action Picture) · UK",
      "Nuffield Dyspraxia Programme · UK (dispraxia verbal)",
      "RAPR — Renfrew Action Picture Procedure · UK",
      // ── AUSTRÁLIA / PACÍFICO ──
      "Spence Children's Communication Checklist · Austrália",
      "CELF-5A — CELF 5th ed adaptação australiana",
      // ── ESCANDINÁVIA / EUROPA CENTRAL ──
      "DIVA — Diagnostisk Inventar for Verbal Assessment · Dinamarca/Alemanha",
      "LittlEARS Auditory Questionnaire · Áustria/30+ países (audição/linguagem pré-verbal)",
      // ── GLOBAL / MULTICULTURAL ──
      "MacArthur-Bates CDI — Communicative Development Inventories · EUA/50+ países (8-36m)",
      "ADOS-2 Módulo 1 (componente de comunicação) · global",
      "GRBAS Scale — Grade, Roughness, Breathiness, Asthenia, Strain · Japão/universal (voz)",
      "Protocolo de Avaliação de Disfagia Pediátrica (Feeding/Swallowing) · internacional",
      "SLP Observation Checklist ASHA (American Speech-Language-Hearing Association) · EUA/referência global",
    ],
    focusPt: "Atraso de linguagem receptiva/expressiva, transtorno fonológico, gagueira, dislalia, dispraxia verbal, comunicação social (TEA), ARFID (seletividade alimentar), bilinguismo, disfagia pediátrica.",
    focusEn: "Receptive/expressive language delay, phonological disorder, stuttering, dyslalia, verbal dyspraxia, social communication (ASD), ARFID (food selectivity), bilingualism, pediatric dysphagia.",
    approachPt: "Avaliação estruturada de linguagem com instrumentos normatizados brasileiros e internacionais. Análise fonológica, semântica, sintática e pragmática. Observação de comunicação funcional em contexto lúdico. 3-5 sessões com a criança e responsável.",
    approachEn: "Structured language assessment with Brazilian and international normed instruments. Phonological, semantic, syntactic and pragmatic analysis. Observation of functional communication in play context. 3-5 sessions with child and guardian.",
  },

  // ── TERAPEUTA OCUPACIONAL ────────────────────────────────
  {
    id: "terapeuta-ocupacional",
    emoji: "🖐️",
    color: "#F97316",
    colorLight: "rgba(249,115,22,0.12)",
    namePt: "Dra. Elena Slagle",
    nameEn: "Dr. Elena Slagle",
    rolePt: "Terapeuta Ocupacional — Integração Sensoriomotora",
    roleEn: "Occupational Therapist — Sensorimotor Integration",
    credentialsPt: "CREFITO-3/000007-TO-F · Especialista em Integração Sensorial e Neurodesenvolvimento",
    credentialsEn: "CREFITO-3/000007-TO-F · Specialist in Sensory Integration and Neurodevelopment",
    bioShortPt: "10 anos em processamento sensorial, desenvolvimento motor e autonomia infantil.",
    bioShortEn: "10 years in sensory processing, motor development and child autonomy.",
    bioLongPt: "Terapeuta Ocupacional especializada em integração sensoriomotora pela abordagem de A. Jean Ayres. Avalia processamento sensorial, desenvolvimento motor fino/grosso, coordenação visomotora, praxia, e autonomia nas AVDs. Referência para TEA/TDAH com componentes sensoriais, TDC e dispraxia.",
    bioLongEn: "Occupational Therapist specialized in sensorimotor integration by A. Jean Ayres approach. Assesses sensory processing, fine/gross motor development, visuomotor coordination, praxis, and ADL autonomy. Reference for ASD/ADHD with sensory components, DCD and dyspraxia.",
    tools: [
      // ── BRASIL ──
      "Perfil Sensorial 2 BR — Sensory Profile 2 (Dunn, 2014) · adaptação brasileira · 0-14a",
      "PEDI-CAT BR — Pediatric Evaluation of Disability Inventory · adaptação brasileira",
      "ACOORDI — Avaliação das Condições para o Aprendizado e Participação · Brasil",
      "MAI — Movement Assessment of Infants · adaptação brasileira (0-12m)",
      "Protocolo de Avaliação de Processamento Sensorial Pediátrico · Brasil",
      "Escala de Independência em AVD para Crianças (EIAVD) · Brasil",
      // ── PROCESSAMENTO SENSORIAL INTERNACIONAL ──
      "SP2 — Sensory Profile 2 (Dunn, 2014) · EUA/35+ países (nascimento-14a11m)",
      "SPM-2 — Sensory Processing Measure 2nd ed (Parham & Ecker) · EUA (5-12a)",
      "SSP — Short Sensory Profile · EUA (diagnóstico rápido)",
      "Infant/Toddler Sensory Profile · EUA (nascimento-35m)",
      "SensOR — Sensory Over-Responsivity Scale · EUA",
      "SIPT — Sensory Integration and Praxis Tests (Ayres) · EUA (4-8a11m · gold standard praxia)",
      "EvalSI — Evaluation in Ayres Sensory Integration (substituto SIPT) · EUA",
      // ── MOTOR INTERNACIONAL ──
      "MABC-2 — Movement Assessment Battery for Children 2nd ed (Henderson) · UK/30+ países (3-16a · gold standard motor)",
      "BOT-2 — Bruininks-Oseretsky Test of Motor Proficiency 2nd ed · EUA (4-21a)",
      "PDMS-3 — Peabody Developmental Motor Scales 3rd ed · EUA (nascimento-5a)",
      "DCDQ-07 — Developmental Coordination Disorder Questionnaire · Canadá/25+ países (5-15a)",
      "M-FUN — Miller Function and Participation Scales · EUA (2½-7a11m)",
      "Harris Infant Neuromotor Test (HINT) · Canadá (2½-12½m)",
      "IMP — Infant Motor Profile · Holanda (2-18m)",
      "Touwen Neurological Examination · Holanda/Europa (reflexos/tônus neurodesenvolvimento)",
      // ── VISOMOTOR / ESCRITA ──
      "VMI-6 — Beery-Buktenica Developmental Test of Visual-Motor Integration 6th ed · EUA/40+ países",
      "DTVP-3 — Developmental Test of Visual Perception 3rd ed · EUA",
      "TVPS-4 — Test of Visual Perceptual Skills 4th ed · EUA",
      // ── FUNCIONAL / PARTICIPAÇÃO ──
      "COPM — Canadian Occupational Performance Measure · Canadá/40+ países",
      "WeeFIM — Functional Independence Measure for Children · EUA/global (0-7a)",
      "AMPS — Assessment of Motor and Process Skills (Fisher) · Dinamarca/25+ países",
      "SCOPE — Short Child Occupational Profile · EUA",
      "COSA — Child Occupational Self-Assessment · EUA (autoavaliação infantil)",
      // ── ALIMENTAÇÃO ──
      "SOS Approach to Feeding Assessment · EUA (ARFID/seletividade sensorial alimentar)",
      "Protocolo de Avaliação de Alimentação Pediátrica (PAFE) · Brasil",
    ],
    focusPt: "Transtorno do Processamento Sensorial (TPS), Transtorno do Desenvolvimento da Coordenação (TDC/DCD), dispraxia, ARFID/seletividade alimentar, disgrafia, dificuldades de AVD, integração sensorial em TEA/TDAH.",
    focusEn: "Sensory Processing Disorder (SPD), Developmental Coordination Disorder (DCD), dyspraxia, ARFID/sensory food selectivity, dysgraphia, ADL difficulties, sensory integration in ASD/ADHD.",
    approachPt: "Avaliação do perfil sensorial (hipo/hipersensibilidade tátil, proprioceptiva, vestibular, visual, auditiva), motricidade fina e grossa, praxia, AVDs. Observação clínica estruturada em ambiente lúdico. 4-6 sessões com observação livre e tarefas estruturadas.",
    approachEn: "Assessment of sensory profile (hypo/hypersensitivity tactile, proprioceptive, vestibular, visual, auditory), fine and gross motor, praxis, ADLs. Structured clinical observation in playful environment. 4-6 sessions with free observation and structured tasks.",
  },

  // ── PSIQUIATRA INFANTIL ──────────────────────────────────
  {
    id: "psiquiatra-infantil",
    emoji: "💊",
    color: "#A855F7",
    colorLight: "rgba(168,85,247,0.12)",
    namePt: "Dr. Rafael Kanner",
    nameEn: "Dr. Rafael Kanner",
    rolePt: "Psiquiatra Infantil & do Adolescente",
    roleEn: "Child & Adolescent Psychiatrist",
    credentialsPt: "CRM SP 000008-F · Residência em Psiquiatria Infantil · Membro AACAP",
    credentialsEn: "CRM SP 000008-F · Child Psychiatry Residency · AACAP Member",
    bioShortPt: "13 anos em psiquiatria infantojuvenil, farmacoterapia e transtornos do humor.",
    bioShortEn: "13 years in child & adolescent psychiatry, pharmacotherapy and mood disorders.",
    bioLongPt: "Psiquiatra infantil com formação em entrevista diagnóstica estruturada, avaliação de humor, psicose precoce, transtornos ansiosos, OCD e farmacoterapia pediátrica. Domina escalas de rastreio e diagnóstico de padrão internacional (EUA, UK, Europa) e avaliação de risco (suicídio, autolesão).",
    bioLongEn: "Child psychiatrist trained in structured diagnostic interviews, mood assessment, early-onset psychosis, anxiety disorders, OCD and pediatric pharmacotherapy. Mastery of international diagnostic and screening scales (USA, UK, Europe) and risk assessment (suicide, self-harm).",
    tools: [
      // ── BRASIL ──
      "K-SADS-PL BR — Kiddie Schedule for Affective Disorders & Schizophrenia (adaptação brasileira)",
      "MINI-KID 7.0 BR — Mini International Neuropsychiatric Interview for Children · adaptação BR",
      "CARS-2 BR — Childhood Autism Rating Scale 2nd ed · adaptação brasileira",
      "CDI-2 BR — Children's Depression Inventory 2nd ed (Kovacs) · adaptação brasileira",
      "CGAS BR — Children's Global Assessment Scale · adaptação brasileira",
      "YSR/ASR BR — Youth Self-Report / Adult Self-Report (Achenbach) · Brasil",
      "GHQ-12 / SQR-20 (rastreio geral saúde mental) · Brasil",
      // ── DIAGNÓSTICO ESTRUTURADO INTERNACIONAL ──
      "K-SADS-PL 2016 — Kiddie SADS Present & Lifetime Version · EUA (gold standard diagnóstico psiquiátrico infantil)",
      "CHIPS — Children's Interview for Psychiatric Syndromes · EUA",
      "DISC-IV — Diagnostic Interview Schedule for Children Version IV · EUA",
      "DAWBA — Development and Well-Being Assessment · UK/global",
      "ChIPS — Child and Adolescent Psychiatric Assessment · EUA/UK",
      "MINI-KID 7.0 — Mini International Neuropsychiatric Interview for Children · internacional",
      // ── DEPRESSÃO ──
      "CDRS-R — Children's Depression Rating Scale–Revised (Poznanski) · EUA (gold standard depressão infantil)",
      "CDI-2 — Children's Depression Inventory 2nd ed · EUA/40+ países",
      "MFQ — Mood and Feelings Questionnaire · UK/global",
      "PHQ-A — Patient Health Questionnaire for Adolescents · EUA/global",
      "BDI-II (adolescentes ≥13a) · EUA/50+ países",
      // ── BIPOLAR / MANIA ──
      "YMRS — Young Mania Rating Scale · EUA/40+ países",
      "CMRS-P — Children's Mania Rating Scale–Parent · EUA",
      "MRS (K-SADS Mania subescala) · EUA",
      // ── ANSIEDADE ──
      "RCADS — Revised Children's Anxiety & Depression Scale · UK/40+ países",
      "MASC-2 — Multidimensional Anxiety Scale for Children · EUA/Canadá",
      "SCARED — Screen for Child Anxiety Related Disorders · EUA/50+ países",
      "Spence CAS — Spence Children's Anxiety Scale · Austrália/30+ países",
      // ── OCD / TOC ──
      "CY-BOCS — Children's Yale-Brown Obsessive Compulsive Scale · EUA (gold standard TOC infantil)",
      "OCI-R — Obsessive-Compulsive Inventory–Revised · EUA/global",
      // ── TRAUMA / PTSD ──
      "CPSS-V — Child PTSD Symptom Scale for DSM-5 · EUA",
      "CPSS-SR-5 — Children's PTSD Symptom Scale Self-Report · EUA",
      "CANS-MH — Child and Adolescent Needs and Strengths · EUA",
      "CAPS-CA-5 — Clinician-Administered PTSD Scale for Children · EUA",
      // ── PSICOSE / GRAVE ──
      "PANSS — Positive & Negative Syndrome Scale · EUA/universal (adolescentes/psicose)",
      "BPRS-CA — Brief Psychiatric Rating Scale for Children & Adolescents · EUA",
      "CGAS — Children's Global Assessment Scale · EUA/universal (funcionamento global)",
      // ── AVALIAÇÃO DE RISCO ──
      "C-SSRS — Columbia Suicide Severity Rating Scale · EUA/universal",
      "SBQ-R — Suicidal Behaviors Questionnaire–Revised · EUA",
      "HoNOSCA — Health of the Nation Outcome Scales for Children & Adolescents · UK/Europa",
      // ── GLOBAL ──
      "SDQ (Total + impacto) · 80+ países",
      "CBCL 6-18 (versão psiquiátrica) · EUA/50+ países",
      "Rutter Scales A/B · UK/Europa",
      "GHQ-12 (responsável) · UK/global",
      "Avaliação farmacoterapêutica pediátrica (indicação, risco/benefício, monitoramento)",
    ],
    focusPt: "Depressão infantil, transtorno bipolar infanto-juvenil, TOC, PTSD/trauma, psicose precoce, TOD, transtorno de conduta, mutismo seletivo, transtorno de apego, avaliação farmacoterapêutica, risco suicida.",
    focusEn: "Childhood depression, pediatric bipolar disorder, OCD, PTSD/trauma, early-onset psychosis, ODD, conduct disorder, selective mutism, attachment disorder, pharmacotherapy assessment, suicide risk.",
    approachPt: "Entrevista diagnóstica estruturada (K-SADS-PL), avaliação de humor e afeto, triagem de psicose, avaliação de risco (C-SSRS), análise de indicação farmacoterapêutica. 2-4 sessões com criança e responsável.",
    approachEn: "Structured diagnostic interview (K-SADS-PL), mood and affect assessment, psychosis screening, risk assessment (C-SSRS), pharmacotherapy indication analysis. 2-4 sessions with child and guardian.",
  },
];

export const getAgentById = (id: AgentId) =>
  AGENT_PROFILES.find((a) => a.id === id);

export const SPECIALISTS = AGENT_PROFILES.filter((a) => !a.isMediator);
export const MEDIATOR = AGENT_PROFILES.find((a) => a.isMediator)!;
