import type { AgentProfile, AgentId } from "@/types";

// ══════════════════════════════════════════════════════════
//  AVISO LEGAL: Todos os profissionais abaixo são
//  PERSONAGENS FICTÍCIOS criados para fins de demonstração.
//  Qualquer semelhança com pessoas reais é mera coincidência.
//  Números de registro são fictícios e identificados com "-F".
// ══════════════════════════════════════════════════════════

export const AGENT_PROFILES: AgentProfile[] = [
  {
    id: "mediator",
    isMediator: true,
    emoji: "🎯",
    color: "#8B5CF6",
    colorLight: "rgba(139,92,246,0.12)",
    namePt: "Coord. Atlas",
    nameEn: "Coord. Atlas",
    rolePt: "Agente Mediador Central",
    roleEn: "Central Mediator Agent",
    credentialsPt: "Sistema de IA — Orquestrador Multiprofissional",
    credentialsEn: "AI System — Multiprofessional Orchestrator",
    bioShortPt: "Coordena a equipe, distribui tarefas e consolida o debate.",
    bioShortEn: "Coordinates the team, distributes tasks and consolidates the debate.",
    bioLongPt: "O Coordenador Atlas é o ponto central de toda a equipe. Responsável por receber os dados, distribuir análises, controlar os turnos do debate, solicitar informações adicionais ao responsável e consolidar o diagnóstico final. Nenhum resultado é emitido sem sua validação.",
    bioLongEn: "Coordinator Atlas is the central point of the entire team. Responsible for receiving data, distributing analyses, controlling debate turns, requesting additional information from the guardian, and consolidating the final diagnosis. No result is issued without its validation.",
    tools: ["Orquestração", "Roteamento", "Consolidação", "Controle de Turno"],
    focusPt: "Coordenação multiprofissional, roteamento de tarefas, síntese diagnóstica.",
    focusEn: "Multiprofessional coordination, task routing, diagnostic synthesis.",
    approachPt: "Garante que todos os agentes concluam sua análise antes de iniciar o debate. Modera os turnos, solicita esclarecimentos e produz o relatório final consensuado.",
    approachEn: "Ensures all agents complete their analysis before starting the debate. Moderates turns, requests clarifications and produces the final consensual report.",
  },
  {
    id: "psi-infantil",
    emoji: "🧒",
    color: "#7C5CFC",
    colorLight: "rgba(124,92,252,0.12)",
    namePt: "Dra. Sofia Vygotski",
    nameEn: "Dr. Sofia Vygotski",
    rolePt: "Psicóloga Infantil",
    roleEn: "Child Psychologist",
    credentialsPt: "CRP 06/000001-F · Especialista em Psicologia do Desenvolvimento",
    credentialsEn: "CRP 06/000001-F · Specialist in Developmental Psychology",
    bioShortPt: "12 anos em avaliação emocional e comportamental infantil.",
    bioShortEn: "12 years in child emotional and behavioral assessment.",
    bioLongPt: "Especialista em transtornos do neurodesenvolvimento com foco em avaliação psicológica infantil. Utiliza abordagem integrativa combinando observação clínica, entrevista lúdica e instrumentos padronizados internacionais. Formada em Psicologia com especialização em Psicologia do Desenvolvimento pela USP (fictícia).",
    bioLongEn: "Specialist in neurodevelopmental disorders with a focus on child psychological assessment. Uses an integrative approach combining clinical observation, play interview and international standardized instruments. Trained in Psychology with specialization in Developmental Psychology.",
    tools: ["SDQ (Strengths & Difficulties Questionnaire)", "M-CHAT-R/F", "SCARED (Ansiedade)", "Vanderbilt ADHD Scales", "PSC-35", "Entrevista Lúdica Estruturada", "CBCL"],
    focusPt: "Desenvolvimento emocional, comportamental e cognitivo. Transtornos de ansiedade, depressão infantil, problemas de conduta, TEA, TDAH.",
    focusEn: "Emotional, behavioral and cognitive development. Anxiety disorders, childhood depression, conduct problems, ASD, ADHD.",
    approachPt: "Observação clínica sistemática, aplicação de escalas padronizadas normatizadas para o Brasil, entrevista com criança e responsável. 4-6 sessões de avaliação.",
    approachEn: "Systematic clinical observation, application of standardized scales normed for Brazil, interview with child and guardian. 4-6 assessment sessions.",
  },
  {
    id: "psi-parentalidade",
    emoji: "👨‍👩‍👧",
    color: "#E5725C",
    colorLight: "rgba(229,114,92,0.12)",
    namePt: "Dr. Victor Winnicott",
    nameEn: "Dr. Victor Winnicott",
    rolePt: "Psicólogo — Parentalidade",
    roleEn: "Psychologist — Parenting",
    credentialsPt: "CRP 05/000002-F · Especialista em Psicologia Familiar e Parentalidade",
    credentialsEn: "CRP 05/000002-F · Specialist in Family Psychology and Parenting",
    bioShortPt: "9 anos em dinâmica familiar e vínculo pais-filhos.",
    bioShortEn: "9 years in family dynamics and parent-child bonding.",
    bioLongPt: "Especializado na avaliação de estilos parentais, dinâmica familiar e seu impacto no desenvolvimento infantil. Formado em Psicologia com pós-graduação em Terapia Familiar Sistêmica e certificação em Parentalidade Positiva.",
    bioLongEn: "Specialized in assessing parenting styles, family dynamics and their impact on child development. Trained in Psychology with postgraduate degree in Systemic Family Therapy and Positive Parenting certification.",
    tools: ["BASC-3 PRQ (Parenting Relationship Questionnaire)", "DPICS-IV (Vídeo-codificação)", "KIPS (Parenting Scale)", "PSDQ (Estilos Parentais)", "PACHIQ-R", "Observação Diádica"],
    focusPt: "Vínculo pais-filhos, estilos parentais (autoritativo/autoritário/permissivo), sintonia emocional, responsividade, impacto do ambiente familiar.",
    focusEn: "Parent-child bond, parenting styles (authoritative/authoritarian/permissive), emotional attunement, responsiveness, family environment impact.",
    approachPt: "Análise observacional de interações pais-filhos com vídeo-codificação, questionários de estilo parental, avaliação de padrões de responsividade e disciplina.",
    approachEn: "Observational analysis of parent-child interactions with video-coding, parenting style questionnaires, assessment of responsiveness and discipline patterns.",
  },
  {
    id: "neuropediatra",
    emoji: "🧠",
    color: "#10B981",
    colorLight: "rgba(16,185,129,0.12)",
    namePt: "Dr. Marco Cajal",
    nameEn: "Dr. Marco Cajal",
    rolePt: "Neuropediatra & Neuropsicopediatra",
    roleEn: "Neuropediatrician & Neuropsychopediatrician",
    credentialsPt: "CRM SP 000004-F · Residência em Neurologia Pediátrica · Título em Neuropsicologia Infantil",
    credentialsEn: "CRM SP 000004-F · Residency in Pediatric Neurology · Title in Child Neuropsychology",
    bioShortPt: "15 anos em neurologia pediátrica, neurodesenvolvimento e avaliação neuropsicológica.",
    bioShortEn: "15 years in pediatric neurology, neurodevelopment and neuropsychological assessment.",
    bioLongPt: "Especialista em neurologia pediátrica e neuropsicologia infantil com dupla atuação. Realiza exame neurológico completo com adaptações etárias, baterias neuropsicológicas abrangentes para mapeamento cognitivo, identificação de déficits específicos e diagnóstico diferencial de transtornos do neurodesenvolvimento. Indica exames complementares quando necessário.",
    bioLongEn: "Specialist in pediatric neurology and child neuropsychology with dual expertise. Performs complete neurological examination with age adaptations, comprehensive neuropsychological batteries for cognitive mapping, identification of specific deficits and differential diagnosis of neurodevelopmental disorders. Indicates complementary exams when necessary.",
    tools: ["Exame Neurológico Pediátrico Padronizado", "Denver Developmental Screening II", "Escala Bayley-III (0-42 meses)", "WISC-V (Inteligência 6-16 anos)", "WPPSI-IV (2-7 anos)", "Conners-3 (TDAH)", "NEPSY-II (Bateria Neuropsicológica)", "Trail Making Test", "FAS (Fluência Verbal)", "Indicação de EEG (se pertinente)", "Indicação de RM Craniana (se pertinente)", "Avaliação de Marcos Motores"],
    focusPt: "Exame neurológico (motor, tônus, reflexos, nervos cranianos, coordenação, marcha), marcos do desenvolvimento neuromotor, avaliação neuropsicológica (inteligência, memória, atenção, funções executivas, velocidade de processamento), diagnóstico diferencial neurológico e cognitivo.",
    focusEn: "Neurological exam (motor, tone, reflexes, cranial nerves, coordination, gait), neuromotor developmental milestones, neuropsychological assessment (intelligence, memory, attention, executive functions, processing speed), neurological and cognitive differential diagnosis.",
    approachPt: "Exame neurológico estruturado com modificações etárias, bateria neuropsicológica abrangente (8-12 horas) com testes normatizados (WISC-V, NEPSY-II), observação qualitativa durante testagem, análise de discrepâncias entre domínios cognitivos, indicação criteriosa de exames complementares.",
    approachEn: "Structured neurological exam with age modifications, comprehensive neuropsychological battery (8-12 hours) with norm-referenced tests (WISC-V, NEPSY-II), qualitative observation during testing, analysis of discrepancies between cognitive domains, judicious indication of complementary exams.",
  },
  {
    id: "bcba",
    emoji: "📊",
    color: "#F59E0B",
    colorLight: "rgba(245,158,11,0.12)",
    namePt: "Dra. Íris Skinner",
    nameEn: "Dr. Iris Skinner",
    rolePt: "Analista do Comportamento — BCBA",
    roleEn: "Behavior Analyst — BCBA",
    credentialsPt: "BCBA Cert. #000005-F · Especialista em ABA e Intervenção Precoce",
    credentialsEn: "BCBA Cert. #000005-F · Specialist in ABA and Early Intervention",
    bioShortPt: "8 anos em análise do comportamento aplicada e intervenção precoce.",
    bioShortEn: "8 years in applied behavior analysis and early intervention.",
    bioLongPt: "Analista do Comportamento Certificada (BCBA) com especialização em intervenção precoce para TEA e atrasos do desenvolvimento. Utiliza ABA baseada em evidências para avaliação funcional, planejamento de intervenção e treinamento de pais.",
    bioLongEn: "Certified Behavior Analyst (BCBA) specializing in early intervention for ASD and developmental delays. Uses evidence-based ABA for functional assessment, intervention planning and parent training.",
    tools: ["VB-MAPP (Verbal Behavior Milestones)", "ABLLS-R (Habilidades Básicas)", "AFLS (Vida Diária)", "FBA (Análise Funcional)", "Preference Assessment", "ABC Data Collection", "PEAK Curriculum"],
    focusPt: "Habilidades verbais e linguagem, comportamentos-alvo e funcionais, autonomia, interação social, análise funcional de comportamentos problema.",
    focusEn: "Verbal skills and language, target and functional behaviors, autonomy, social interaction, functional analysis of problem behaviors.",
    approachPt: "Avaliação baseada em marcos comportamentais, análise funcional do comportamento-problema, coleta sistemática de dados, planejamento curricular ABA individualizado.",
    approachEn: "Behavioral milestone-based assessment, functional analysis of problem behavior, systematic data collection, individualized ABA curriculum planning.",
  },
];

export const getAgentById = (id: AgentId) =>
  AGENT_PROFILES.find((a) => a.id === id);

export const SPECIALISTS = AGENT_PROFILES.filter((a) => !a.isMediator);
export const MEDIATOR = AGENT_PROFILES.find((a) => a.isMediator)!;
